document.documentElement.classList.add('js');
const products=[
["MiQd Business Worker","Daily operations and action control in one focused dashboard: priorities, owners, workload, client requests, SOPs and weekly review.","Denná prevádzka a kontrola úloh v jednom paneli: priority, zodpovednosti, kapacita, požiadavky klientov, postupy a týždenná kontrola.","business","MWSo0","€24.90","OPERATE · EXECUTE · CONTROL"],
["MiQd GetPaid","Track invoices, partial payments and overdue work, then prepare the right follow-up message and export your records.","Sledujte faktúry, čiastočné platby a omeškania, pripravte správnu upomienku a exportujte svoje záznamy.","finance","QXaLJ","€19.90","TRACK · FOLLOW UP · COLLECT"],
["MiQd Contractor","A mobile-first job quote and profit-control tool for labour, materials, extras, customer price and expected margin.","Mobilný nástroj na ponuky a kontrolu zisku: práca, materiál, dodatočné náklady, cena pre zákazníka a marža.","finance","HLZ4f","€19.90","QUOTE · COST · PROFIT"],
["Solopreneur Operating System","Run a business alone with visible priorities, projects, sales activity, money signals and decisions.","Riaďte samostatné podnikanie s jasnými prioritami, projektmi, predajom, financiami a rozhodnutiami.","business","265kB","€29.90","PLAN · EXECUTE · REVIEW"],
["Digital Product Launch System","Shape, package, position and launch a digital product with a clear offer and practical sales path.","Vytvorte, zabaľte, odlíšte a spustite digitálny produkt s jasnou ponukou a praktickou cestou k predaju.","business","4gLCR","€24.90","BUILD · RELEASE · SELL"],
["AI Job Search & Career Kit","Improve your CV, applications and interview preparation with practical, responsible AI workflows.","Zlepšite životopis, žiadosti a prípravu na pohovor pomocou praktických a zodpovedných AI postupov.","career","jphGt","€19.90","POSITION · APPLY · INTERVIEW"],
["Local Business Growth Kit","Improve local visibility, reviews, customer offers and repeat business with a focused growth system.","Zlepšite lokálnu viditeľnosť, recenzie, ponuky a návrat zákazníkov pomocou cieleného systému rastu.","business","p1OJ2","€24.90","ATTRACT · CONVERT · RETURN"],
["Small Business Finance Dashboard","Track cash flow, profit, costs and essential financial signals without losing sight of what matters.","Sledujte cash flow, zisk, náklady a hlavné finančné ukazovatele bez straty prehľadu.","finance","Aiua8","€34.90","TRACK · REVIEW · DECIDE"],
["AI Email & Communication Vault","Write clearer client emails, replies, difficult messages and follow-ups without starting from zero.","Píšte jasnejšie e-maily, odpovede, náročné správy a pripomienky bez začínania od nuly.","ai","n42EC","€24.90","WRITE · REPLY · FOLLOW UP"],
["Freelancer Client Acquisition System","Define your offer, find prospects, start conversations and follow up with a repeatable workflow.","Definujte ponuku, nájdite klientov, začnite komunikáciu a postupujte podľa opakovateľného procesu.","business","rPq7T","€24.90","FIND · WIN · RETAIN"],
["Contractor Profit System","An editable quote calculator, job-cost tracker and profit toolkit for trades and construction businesses.","Upraviteľná kalkulačka ponúk, nákladov zákazky a zisku pre remeslá a stavebné firmy.","finance","BoQ7T","€29.90","CALCULATE · QUOTE · CONTROL"],
["AI Sales Machine","Build a repeatable sales pipeline for prospecting, outreach, follow-up and stronger pitches.","Vytvorte opakovateľný predajný proces pre vyhľadávanie klientov, oslovenie, komunikáciu a lepšie ponuky.","ai","pPAxI","€29.90","PROSPECT · PITCH · CLOSE"],
["Small Business Command Center","Keep priorities, projects, sales, finances and key decisions visible in one practical business system.","Udržte priority, projekty, predaj, financie a rozhodnutia prehľadne v jednom firemnom systéme.","business","X2Hv8","€29.90","PLAN · TRACK · DECIDE"],
["From €0 to Your First Digital Product","Validate an idea, build the offer and move from a blank page to your first sellable digital product.","Overte nápad, vytvorte ponuku a prejdite od prázdnej strany k prvému predajnému digitálnemu produktu.","business","WFEhu","€14.90","VALIDATE · BUILD · SELL"],
["Social Media Content Factory","A 30-day system for turning ideas into consistent, useful social content without daily guesswork.","30-dňový systém na premenu nápadov na pravidelný a užitočný obsah bez každodenného tápania.","ai","NG6dF","€14.90","IDEA · CREATE · PUBLISH"],
["1000 AI Prompts Framework","A structured prompt framework for work, business and life—organized for practical use, not random copying.","Štruktúrovaný rámec AI promptov pre prácu, podnikanie a život, usporiadaný na praktické použitie.","ai","Lsm5D","€14.90","ASK · REFINE · APPLY"],
["Ultimate Freelancer Starter Kit","A practical foundation from proposal and onboarding to delivery, communication and getting paid.","Praktický základ od ponuky a onboardingu až po dodanie práce, komunikáciu a získanie platby.","business","3s1HE","€14.90","PROPOSE · DELIVER · GROW"],
["AI for Construction & Trades","Use AI for quotes, site records, customer communication and everyday trade-business administration.","Využite AI na ponuky, záznamy zo stavby, komunikáciu so zákazníkmi a každodennú administratívu.","ai","KnA0V","€14.90","QUOTE · RECORD · COMMUNICATE"],
["Small Business AI Pack","Practical AI workflows for operations, documents, customer communication and everyday business tasks.","Praktické AI postupy pre prevádzku, dokumenty, zákaznícku komunikáciu a každodenné firemné úlohy.","ai","YC20a","€14.90","OPERATE · WRITE · IMPROVE"],
["AI Marketing Machine","Plan content, email and campaigns with a reusable AI-assisted marketing workflow.","Plánujte obsah, e-maily a kampane pomocou opakovateľného marketingového systému s podporou AI.","ai","0XLVd","€14.90","PLAN · CREATE · CAMPAIGN"],
["AI Side Hustle Blueprint","Explore 30 AI business models and turn the right idea into a focused, testable side-business plan.","Preskúmajte 30 AI biznis modelov a premeňte vhodný nápad na konkrétny a testovateľný plán.","ai","ytz1s","€14.90","DISCOVER · VALIDATE · START"],
["AI ako skutočný zamestnanec","Praktická slovenská príručka na využitie AI ako spoľahlivého pomocníka v podnikaní a práci.","Praktická slovenská príručka na využitie AI ako spoľahlivého pomocníka v podnikaní a práci.","ai","MgwyG","€14.90","NASTAVTE · DELEGUJTE · ZLEPŠUJTE"],
["The AI Workforce Playbook","Turn AI into a practical work partner through clear roles, repeatable workflows and quality control.","Premeňte AI na praktického pracovného partnera pomocou jasných rolí, postupov a kontroly kvality.","ai","74upI","€14.90","DESIGN · DELEGATE · REVIEW"],
["DREAM","A simple Android tool that turns every saving decision into visible progress toward the future you want.","Jednoduchý Android nástroj, ktorý mení každé rozhodnutie ušetriť na viditeľný pokrok k vášmu cieľu.","finance","YJzlr","€1.90","SAVE · SEE · REACH"],
["Money Reset","A guided 30-day financial reset system for rebuilding awareness, habits and control over everyday money.","Riadený 30-dňový finančný reštart na obnovu prehľadu, návykov a kontroly nad každodennými peniazmi.","finance","AurOY","€14.90","RESET · TRACK · CONTROL"],
["30-Day Money Making Planner","A focused monthly planner for turning income ideas into daily actions, progress and review.","Cielený mesačný plánovač na premenu príjmových nápadov na denné kroky, pokrok a kontrolu.","finance","uWY0N","€14.90","PLAN · ACT · EARN"]];
const palette=["gold","green","violet","coral","blue","amber","rose","teal","forest","orange","indigo","red"],grid=document.getElementById("productGrid");
function renderProducts(){if(!grid)return;const lang=document.documentElement.lang==="sk"?"sk":"en";grid.innerHTML=products.map((p,i)=>`<article class="product-card ${i<3?"featured":""}" data-category="${p[3]}"><div class="product-art art-${palette[i%palette.length]}"><small>MiQd.</small><strong>${p[0]}</strong><span>${p[6]}</span><i>${String(i+1).padStart(2,"0")}</i></div><b>${p[3].toUpperCase()}</b><h3>${p[0]}</h3><p>${lang==="sk"?p[2]:p[1]}</p><div class="card-bottom"><strong class="price">${p[5]}</strong><a class="card-action" href="https://payhip.com/b/${p[4]}" target="_blank" rel="noopener">${lang==="sk"?"Kúpiť na Payhip ↗":"Buy on Payhip ↗"}</a></div></article>`).join("");applyFilter(document.querySelector(".filters .active")?.dataset.filter||"all");observeCards()}
const toggle=document.getElementById("langToggle"),menu=document.getElementById("langMenu"),langButtons=document.querySelectorAll("[data-lang]");if(toggle&&menu){toggle.addEventListener("click",e=>{e.stopPropagation();const open=menu.classList.toggle("open");toggle.setAttribute("aria-expanded",String(open))});document.addEventListener("click",()=>{menu.classList.remove("open");toggle.setAttribute("aria-expanded","false")});menu.addEventListener("click",e=>e.stopPropagation())}function setLanguage(lang){document.documentElement.lang=lang;document.querySelectorAll("[data-en][data-sk]").forEach(el=>el.innerHTML=el.dataset[lang]);langButtons.forEach(btn=>btn.classList.toggle("active",btn.dataset.lang===lang));try{localStorage.setItem("miqd-lang",lang)}catch(e){}if(menu)menu.classList.remove("open");renderProducts()}let saved="en";try{saved=localStorage.getItem("miqd-lang")||((navigator.language||"").toLowerCase().startsWith("sk")?"sk":"en")}catch(e){}setLanguage(saved==="sk"?"sk":"en");langButtons.forEach(btn=>btn.addEventListener("click",()=>setLanguage(btn.dataset.lang)));function applyFilter(filter){document.querySelectorAll(".product-card").forEach(card=>card.hidden=filter!=="all"&&card.dataset.category!==filter)}document.querySelectorAll("[data-filter]").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("[data-filter]").forEach(b=>b.classList.toggle("active",b===btn));applyFilter(btn.dataset.filter)}));function observeCards(){const cards=document.querySelectorAll(".product-card,.grid article,.steps>div,.why>div,.trust>div");if(!("IntersectionObserver"in window)){cards.forEach(c=>c.classList.add("revealed"));return}const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("revealed");observer.unobserve(e.target)}}),{threshold:.05});cards.forEach((c,i)=>{c.classList.add("reveal");c.style.setProperty("--delay",`${Math.min(i%3,2)*45}ms`);observer.observe(c)})}observeCards();